name: Greetings

on: [pull_request, issues]

jobs:
  creating:
    runs-on: ubuntu-latest
    steps:
    - uses: AkhilAchanta/action-create-branch@v2.0.1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       branch: 'feature'
